### ISSUE TITLE
Add better error on export if chrome is not installed

### ISSUE THREAD

**Issue by bitspittle** [varabyte/kobweb#165]
Right now, you get something like:

```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':kobwebExport'.
        at ... org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:147)
Caused by: java.lang.RuntimeException: Could not find chrome binary! Try setting CHROME_PATH env to chrome binary path.
        at com.github.kklisura.cdt.launch.ChromeLauncher.getChromeBinaryPath(ChromeLauncher.java:216)
        at com.github.kklisura.cdt.launch.ChromeLauncher.launch(ChromeLauncher.java:163)
        ...
```

It might be nice if export could immediately show a clear error message to users before even running Gradle if chrome isn't present. At least, maybe a try/catch around attempting to use Chrome in export code.

**Comment by bitspittle** [comment]
This is no longer an issue now that we delegate browser installation to Playwright.
