### ISSUE TITLE
Can't run kobwen run on newly created project

### ISSUE THREAD

**Issue by Altantur** [varabyte/kobweb#229]
*YOUR BUG DESCRIPTION HERE*

If relevant, specify:
* OS: Mac/M1
* Kobweb libs version: 0.13.0
* Kobweb CLI version: 0.9.12

---
Hi, I've been doing some projects with Compose HTML library, this looks like exactly what I wanted. But after fresh/first-time installation through brew. When I try to run `kobweb run` in the site dir, I have the following error:

```sh
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':site:compileKotlinJvm'.
> No matching toolchains found for requested specification: {languageVersion=11, vendor=any, implementation=vendor-specific}.
   > No locally installed toolchains match (see https://docs.gradle.org/8.0.2/userguide/toolchains.html#sec:auto_detection) and toolchain download repositories have not been configured (see https://docs.gradle.org/8.0.2/userguide/toolchains.html#sub:download_repositories).

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.internal.tasks.TaskDependencyResolveException: Could not determine the dependencies of task ':site:compileKotlinJvm'.
	at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.getDependencies(CachingTaskDependencyResolveContext.java:68)
	at org.gradle.execution.plan.TaskDependencyResolver.resolveDependenciesFor(TaskDependencyResolver.java:49)
```

**Comment by Altantur** [comment]
Thanks for the quick reply. I'm confirming it is working as expected after JDK 11 installation.
