### ISSUE TITLE
Having a native dependency breaks Kobweb server reloading 

### ISSUE THREAD

**Issue by bitspittle** [varabyte/kobweb#241]
Reported from a user...

* Use realm as a dependency
* modify an API route (to get it to reload)
```
caused by: java.lang. Unsatisfi edLi nkError: Native Library C:
\Users\...\AppData\ Local\i0-realm-kotlin\ f7 113120ba00balff9ld696eecd3919e85a4e34e\ realmc
.dll already loaded in another classloader
```

**Comment by tusxxx** [comment]
First error stack trace
```
java.lang.ExceptionInInitializerError
	at io.realm.kotlin.internal.interop.RealmInterop.realm_set_log_callback(RealmInterop.kt:1208)
	at io.realm.kotlin.log.RealmLog.<clinit>(RealmLog.kt:49)
	at io.realm.kotlin.RealmConfiguration$Builder.build(RealmConfiguration.kt:138)
	at io.realm.kotlin.RealmConfiguration$Companion.create(RealmConfiguration.kt:170)
	at org.example.dbkursovaya.database.MongoDB$config$2.invoke(MongoDB.kt:9)
	at org.example.dbkursovaya.database.MongoDB$config$2.invoke(MongoDB.kt:9)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.example.dbkursovaya.database.MongoDB.getConfig(MongoDB.kt:9)
	at org.example.dbkursovaya.database.MongoDB.access$getConfig(MongoDB.kt:8)
	at org.example.dbkursovaya.database.MongoDB$realm$2.invoke(MongoDB.kt:10)
	at org.example.dbkursovaya.database.MongoDB$realm$2.invoke(MongoDB.kt:10)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.example.dbkursovaya.database.MongoDB.getRealm(MongoDB.kt:10)
	at org.example.dbkursovaya.database.MongoDB.access$getRealm(MongoDB.kt:8)
	at org.example.dbkursovaya.database.MongoDB$setCustomers$2.invokeSuspend(MongoDB.kt:14)
	at org.example.dbkursovaya.database.MongoDB$setCustomers$2.invoke(MongoDB.kt)
	at org.example.dbkursovaya.database.MongoDB$setCustomers$2.invoke(MongoDB.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at org.example.dbkursovaya.database.MongoDB.setCustomers(MongoDB.kt:13)
	at org.example.dbkursovaya.api.DatabaseApiKt.customers(DatabaseApi.kt:12)
caused by: java.lang.RuntimeException: Couldn't load Realm native libraries
	at io.realm.kotlin.internal.interop.realmc.<clinit>(realmc.java:28)
caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.realm.kotlin.internal.interop.realmc.<clinit>(realmc.java:26)
	at io.realm.kotlin.internal.interop.RealmInterop.realm_set_log_callback(RealmInterop.kt:1208)
	at io.realm.kotlin.log.RealmLog.<clinit>(RealmLog.kt:49)
	at io.realm.kotlin.RealmConfiguration$Builder.build(RealmConfiguration.kt:138)
	at io.realm.kotlin.RealmConfiguration$Companion.create(RealmConfiguration.kt:170)
	at org.example.dbkursovaya.database.MongoDB$config$2.invoke(MongoDB.kt:9)
	at org.example.dbkursovaya.database.MongoDB$config$2.invoke(MongoDB.kt:9)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.example.dbkursovaya.database.MongoDB.getConfig(MongoDB.kt:9)
	at org.example.dbkursovaya.database.MongoDB.access$getConfig(MongoDB.kt:8)
	at org.example.dbkursovaya.database.MongoDB$realm$2.invoke(MongoDB.kt:10)
	at org.example.dbkursovaya.database.MongoDB$realm$2.invoke(MongoDB.kt:10)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.example.dbkursovaya.database.MongoDB.getRealm(MongoDB.kt:10)
	at org.example.dbkursovaya.database.MongoDB.access$getRealm(MongoDB.kt:8)
	at org.example.dbkursovaya.database.MongoDB$setCustomers$2.invokeSuspend(MongoDB.kt:14)
	at org.example.dbkursovaya.database.MongoDB$setCustomers$2.invoke(MongoDB.kt)
	at org.example.dbkursovaya.database.MongoDB$setCustomers$2.invoke(MongoDB.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at org.example.dbkursovaya.database.MongoDB.setCustomers(MongoDB.kt:13)
	at org.example.dbkursovaya.api.DatabaseApiKt.customers(DatabaseApi.kt:12)
caused by: java.lang.UnsatisfiedLinkError: Native Library C:\Users\tusxd\AppData\Local\io-realm-kotlin\f7113120ba00ba1ff91d696eecd3919e85a4e34e\realmc.dll already loaded in another classloader
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:201)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at io.realm.kotlin.jvm.SoLoader.load(SoLoader.kt:83)
	at io.realm.kotlin.jvm.SoLoader.load(SoLoader.kt:60)
```

If trying relaunch stacktrace
```
java.lang.NoClassDefFoundError: Could not initialize class io.realm.kotlin.log.RealmLog
	at io.realm.kotlin.RealmConfiguration$Builder.build(RealmConfiguration.kt:138)
	at io.realm.kotlin.RealmConfiguration$Companion.create(RealmConfiguration.kt:170)
	at org.example.dbkursovaya.database.MongoDB$config$2.invoke(MongoDB.kt:9)
	at org.example.dbkursovaya.database.MongoDB$config$2.invoke(MongoDB.kt:9)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.example.dbkursovaya.database.MongoDB.getConfig(MongoDB.kt:9)
	at org.example.dbkursovaya.database.MongoDB.access$getConfig(MongoDB.kt:8)
	at org.example.dbkursovaya.database.MongoDB$realm$2.invoke(MongoDB.kt:10)
	at org.example.dbkursovaya.database.MongoDB$realm$2.invoke(MongoDB.kt:10)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.example.dbkursovaya.database.MongoDB.getRealm(MongoDB.kt:10)
	at org.example.dbkursovaya.database.MongoDB.access$getRealm(MongoDB.kt:8)
	at org.example.dbkursovaya.database.MongoDB$setCustomers$2.invokeSuspend(MongoDB.kt:14)
	at org.example.dbkursovaya.database.MongoDB$setCustomers$2.invoke(MongoDB.kt)
	at org.example.dbkursovaya.database.MongoDB$setCustomers$2.invoke(MongoDB.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at org.example.dbkursovaya.database.MongoDB.setCustomers(MongoDB.kt:13)
	at org.example.dbkursovaya.api.DatabaseApiKt.customers(DatabaseApi.kt:12)
	```

My build.gradle - https://gist.github.com/tusxxx/b4dececcaad60c0078416749d6649cc7

**Comment by bitspittle** [comment]
After skimming https://www.mongodb.com/docs/realm/sdk/kotlin/quick-start/, I have repro steps that work with the Kobweb project:

* Sync Kobweb
* Download and unzip the following patch somewhere on your machine
[kobweb-helloworld-realm-patch.zip](https://github.com/varabyte/kobweb/files/11479593/kobweb-helloworld-realm-patch.zip)
  * Sorry that I had to zip it! GitHub wouldn't accept the patch otherwise.
* `cd kobweb/examples/helloworld`
* `git apply path/to/patch`

At this point, the patch should have applied successfully. Then...

* `kobweb run`
* Once running, visit `http://localhost:8080/api/hello`
* Go into hello.kt, change something, it doesn't matter (e.g. "Init hello" --> "Init hello 2")
* Wait for kobweb CLI to rebuild stuff
* Once done, visit `http://localhost:8080/api/hello` again.
* BAM, error callstack.
